name: Build Android 15 6.6 GKI Kernels

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      runner:
        required: true
        type: string
      lto_type:
        required: true
        type: string
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string

jobs:
  build-kernel-a15-6-6-kernelsu-susfs:
    strategy:
      matrix:
        include:
          - android_version: "android15"
            kernel_version: "6.6"
            sub_level: "30"
            os_patch_level: "2024-08"

    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      android_version: "android15"
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      runner: ${{ inputs.runner }}
      lto_type: ${{ inputs.lto_type }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
